name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: Swatinem/rust-cache@v2
    - run: cargo fmt --all --check
    - run: cargo build --all-targets --all-features
    - name: unit tests with coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        path: lcov.info
    - run: cargo test --all-features
    - run: cargo clippy --all-features
    - run: cargo doc --no-deps --all-features
    - name: Send to coveralls
      uses: coverallsapp/github-action@v2.3.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
